FromLectures/week11/demo/api1/urls.py
from django.urls import path
from api1 import views


urlpatterns = [
    path('index/', views.index),
    path('students/', views.student_list),
    path('students/<int:pk>/', views.student_detail),
]

FromLectures/week11/demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('auth_.urls')),
    path('main2/', include('main2.urls')),
    path('api1/', include('api1.urls')),
    path('api2/', include('api2.urls')),
]

FromLectures/week11/demo/main2/urls.py
from django.urls import path
from main2 import views

app_name = 'main2'

urlpatterns = [
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(template_name='contact.html'), name='contact'),
    path('students/', views.StudentListView.as_view(), name='student_list'),
    path('students/<int:pk>/', views.StudentDetailView.as_view(), name='student_detail'),
    path('students/create/', views.StudentCreateView.as_view(), name='student_create'),
    path('students/<int:pk>/update/', views.StudentUpdateView.as_view(), name='student_update'),
    path('students/<int:pk>/delete/', views.StudentDeleteView.as_view(), name='student_delete')
]

FromLectures/week11/demo/main2/models.py
from django.db import models
from django.urls import reverse_lazy
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=200)


class Comment(models.Model):
    text = models.TextField(max_length=500)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')


class StudentManager(models.Manager):
    def for_user(self, user):
        return self.filter(created_by=user)


class Student(models.Model):
    name = models.CharField(max_length=200)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name='students')

    objects = StudentManager()

    def __str__(self):
        return self.name

    def to_json(self):
        return {
            'id': self.id,
            'name': self.name,
            'user': self.created_by.username if self.created_by else None
        }

    def get_absolute_url(self):
        return reverse_lazy('main2:student_list')

FromLectures/week11/demo/main2/forms.py
from django.forms import ModelForm
from main2.models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ['name', ]

FromLectures/week11/demo/main2/views/const_templates.py
from django.views.generic import TemplateView


class AboutView(TemplateView):
    template_name = 'about.html'
    http_method_names = ['get']


class ContactView(AboutView):
    pass

FromLectures/week11/demo/main2/views/student.py
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from django.contrib.auth.mixins import LoginRequiredMixin

from main2.models import Student
from main2.forms import StudentForm


class StudentListView(LoginRequiredMixin, ListView):
    model = Student
    context_object_name = 'students'


class StudentDetailView(LoginRequiredMixin, DetailView):
    model = Student


class StudentCreateView(LoginRequiredMixin, CreateView):
    model = Student
    fields = ['name']
    success_url = reverse_lazy('main2:student_list')

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class StudentUpdateView(LoginRequiredMixin, UpdateView):
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy('main2:student_list')

    def get_queryset(self):
        return Student.objects.for_user(user=self.request.user)


class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy('main2:student_list')

    def get_queryset(self):
        return Student.objects.for_user(user=self.request.user)

FromLectures/week11/demo/main2/templates/main2/student_confirm_delete.html
{% extends 'base.html' %}

{% block body %}
    <h1>Delete Student: {{ object }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Delete" class="btn btn-danger">
    </form>
{% endblock %}

FromLectures/week11/demo/main2/templates/main2/student_detail.html
{% extends 'base.html' %}

{% block body %}
    <a class="btn btn-info" href="{% url 'main2:student_list' %}">Back</a>
    <h1>Student: {{ object }} </h1>
{% endblock %}

FromLectures/week11/demo/main2/templates/main2/student_form.html
{% extends 'base.html' %}

{% block body %}

    <div class="row">
        <div class="col-xs-6 col-xs-offset-3">

            <h1>Student
            {% if form.name.value != None %}
                Update
            {% else %}
                Add
            {% endif %}
            </h1>
            <form action="." method="post">
                {% csrf_token %}
{#                {{ form }}#}
                <div class="form-group">
                    <input type="text" name="{{ form.name.name }}"
                          {% if form.name.value != None %}
                              value="{{ form.name.value }}"
                          {% endif %}
                           class="form-control">
                </div>
                <input type="submit" class="btn btn-default pull-right">
            </form>

        </div>
    </div>

{% endblock %}

FromLectures/week11/demo/main2/templates/main2/student_list.html
{% extends 'base.html' %}

{% block body %}
    <a class="btn btn-primary" href="{% url 'main2:student_create' %}">Add new Student</a>

    <h1>Student list</h1>

    <ul class="list-group">
        {% for student in students %}

            <li class="list-group-item">
                <div>
                    <h4><a href="{% url 'main2:student_detail' student.id %}">{{ student.name }}</a></h4>
                    <h5>Created by: {{ student.created_by }}</h5>
                </div>
                {% if user == student.created_by %}
                    <div class="actions text-right">
                        <a class="btn btn-xs btn-info" href="{% url 'main2:student_update' student.id %}">Update</a>
                        <a class="btn btn-xs btn-danger" href="{% url 'main2:student_delete' student.id %}">Delete</a>
                    </div>
                {% endif %}
            </li>

        {% endfor %}
    </ul>
{% endblock %}