FromLectures/week11/demo/api1/urls.py
from django.urls import path
from api1 import views


urlpatterns = [
    path('index/', views.index),
    path('students/', views.student_list),
    path('students/<int:pk>/', views.student_detail),
]

FromLectures/week11/demo/demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('auth_.urls')),
    path('main2/', include('main2.urls')),
    path('api1/', include('api1.urls')),
    path('api2/', include('api2.urls')),
]

FromLectures/week11/demo/main/urls.py
from django.urls import path
from main import views

urlpatterns = [
    path('', views.home, name='home'),
    path('authors/', views.author_list, name='author_list'),
    path('authors/<int:author_id>', views.author_detail, name='author_detail'),
    path('authors/new/', views.author_new, name='author_new'),

    path('books/', views.book_list, name='book_list'),
    path('show_color/', views.show_color),
    path('set_color/', views.set_color),

]

FromLectures/week11/demo/main2/urls.py
from django.urls import path
from main2 import views

app_name = 'main2'

urlpatterns = [
    path('about/', views.AboutView.as_view(), name='about'),
    path('contact/', views.ContactView.as_view(template_name='contact.html'), name='contact'),
    path('students/', views.StudentListView.as_view(), name='student_list'),
    path('students/<int:pk>/', views.StudentDetailView.as_view(), name='student_detail'),
    path('students/create/', views.StudentCreateView.as_view(), name='student_create'),
    path('students/<int:pk>/update/', views.StudentUpdateView.as_view(), name='student_update'),
    path('students/<int:pk>/delete/', views.StudentDeleteView.as_view(), name='student_delete')
]

FromLectures/week11/demo/main/models.py
from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Country'
        verbose_name_plural = 'Countries'

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=100)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cities'

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    website = models.URLField()
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    # city = models.CharField(max_length=100)
    # country = models.CharField(max_length=100)

    def __str__(self):
        return "#{}: {}".format(self.id, self.name)


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.email


class Book(models.Model):
    title = models.CharField(max_length=100)
    publication_date = models.DateTimeField()
    num_pages = models.IntegerField(default=10)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='books')
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

FromLectures/week11/demo/main/forms.py
from django import forms
from main.models import Author


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ('first_name', 'last_name', 'email')

FromLectures/week11/demo/main/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from main.models import Author
from main.forms import AuthorForm
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required


def home(request):
    return render(request, 'home.html')


@login_required
def author_list(request):
    # if request.user.is_authenticated:
    authors = Author.objects.all()
    context = {
        'authors': authors
    }
    return render(request, 'author/list.html', context)
    # return redirect('login')


@login_required
def author_detail(request, author_id):
    try:
        author = Author.objects.get(id=author_id)
    except Author.DoesNotExist:
        raise Http404("Author not found")
    context = {
        'author': author,
        'books': author.books.all()
    }
    return render(request, 'author/detail.html', context)


@login_required
def author_new(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('author_list')
    else:
        form = AuthorForm()
    context = {
        'form': form
    }
    return render(request, 'author/new.html', context)


@login_required
def book_list(request):
    return render(request, 'book/list.html')


def show_color(request):
    if 'color' in request.COOKIES:
        return HttpResponse('Your color: {}'.format(request.COOKIES['color']))
    return HttpResponse("Your color empty")


def set_color(request):
    if 'color' in request.GET:
        response = HttpResponse('Your color is now {}'.format(request.GET['color']))
        response.set_cookie('color', request.GET['color'])
        return response
    else:
        return HttpResponse("You didn't give a color.")

FromLectures/week11/demo/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>

    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <div class="navbar-brand">
                    <a href="{% url 'home' %}">
                        Demo
                    </a>
                </div>
            </div>

            {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'book_list' %}">Books</a>
                    </li>
                    <li>
                        <a href="{% url 'author_list' %}">Authors</a>
                    </li>
                    <li>
                        <a href="{% url 'main2:student_list' %}">Student</a>
                    </li>
                    <li>
                        <a href="{% url 'main2:about' %}">About</a>
                    </li>
                    <li>
                        <a href="{% url 'main2:contact' %}">Contact</a>
                    </li>
                </ul>
            {% endif %}

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li>
                        <a href="">{{ user }}</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'login' %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url 'register' %}">Register</a>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>

    <div class="container">
        {% block body %}

        {% endblock %}
    </div>


</body>
</html>

FromLectures/week11/demo/main/templates/home.html
{% extends 'base.html' %}

{% block body %}

    {% if user.is_authenticated %}
        <h2>Welcome, {{ user.username }}. Thanks for logging in.</h2>
    {% else %}
        <h2>Welcome, new user. Please log in.</h2>
    {% endif %}

{% endblock %}